/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateComplaintBodyRoadType } from "./createComplaintBodyRoadType";
import type { CreateComplaintBodyType } from "./createComplaintBodyType";

export interface CreateComplaintBody {
  type: CreateComplaintBodyType;
  road_type: CreateComplaintBodyRoadType;
  authority: string;
  description: string;
  contact_name?: string;
  contact_email?: string;
}
