/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */

export type CreateComplaintBodyRoadType =
  (typeof CreateComplaintBodyRoadType)[keyof typeof CreateComplaintBodyRoadType];

export const CreateComplaintBodyRoadType = {
  NH: "NH",
  SH: "SH",
  MDR: "MDR",
  City_Road: "City Road",
  Rural_Road: "Rural Road",
  Unknown: "Unknown",
} as const;
