/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */

export type CreatePotholeBodySeverity =
  (typeof CreatePotholeBodySeverity)[keyof typeof CreatePotholeBodySeverity];

export const CreatePotholeBodySeverity = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Critical: "Critical",
} as const;
