/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */

export type ListPotholesSeverity =
  (typeof ListPotholesSeverity)[keyof typeof ListPotholesSeverity];

export const ListPotholesSeverity = {
  Low: "Low",
  Medium: "Medium",
  High: "High",
  Critical: "Critical",
} as const;
