/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import type { ListPotholesDateRange } from "./listPotholesDateRange";
import type { ListPotholesSeverity } from "./listPotholesSeverity";

export type ListPotholesParams = {
  severity?: ListPotholesSeverity;
  dateRange?: ListPotholesDateRange;
  lat?: number;
  lon?: number;
  /**
   * Radius in meters
   */
  radius?: number;
  is_fixed?: boolean;
};
