/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */

export type ListPotholesDateRange =
  (typeof ListPotholesDateRange)[keyof typeof ListPotholesDateRange];

export const ListPotholesDateRange = {
  "24h": "24h",
  week: "week",
  month: "month",
  all: "all",
} as const;
