/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import type { PotholeSeverity } from "./potholeSeverity";

export interface Pothole {
  id: string;
  lat: number;
  lon: number;
  severity: PotholeSeverity;
  depth_cm: number;
  width_cm: number;
  volume_m3: number;
  estimated_repair_cost_usd: number;
  image_base64?: string | null;
  is_fixed: boolean;
  votes: number;
  confidence: number;
  timestamp: string;
  address?: string | null;
}
