/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import type { Pothole } from "./pothole";
import type { RouteResponseGeometry } from "./routeResponseGeometry";

export interface RouteResponse {
  /** GeoJSON geometry */
  geometry: RouteResponseGeometry;
  distance_m: number;
  duration_s: number;
  pothole_warnings: Pothole[];
  has_danger: boolean;
  total_repair_cost_on_route: number;
}
