/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */

export interface StatsSummary {
  total_potholes: number;
  total_fixed: number;
  high_severity: number;
  total_repair_cost_usd: number;
  total_volume_m3: number;
  total_asphalt_tons: number;
  potholes_24h: number;
  avg_depth_cm: number;
  city_savings_usd: number;
}
