/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import type { UpdatePotholeBodySeverity } from "./updatePotholeBodySeverity";

export interface UpdatePotholeBody {
  is_fixed?: boolean;
  severity?: UpdatePotholeBodySeverity;
}
