/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Cyberpunk Pothole Detection & Routing System API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all potholes
 */
export const ListPotholesQueryParams = zod.object({
  severity: zod.enum(["Low", "Medium", "High", "Critical"]).optional(),
  dateRange: zod.enum(["24h", "week", "month", "all"]).optional(),
  lat: zod.coerce.number().optional(),
  lon: zod.coerce.number().optional(),
  radius: zod.coerce.number().optional().describe("Radius in meters"),
  is_fixed: zod.coerce.boolean().optional(),
});

export const ListPotholesResponseItem = zod.object({
  id: zod.string(),
  lat: zod.number(),
  lon: zod.number(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]),
  depth_cm: zod.number(),
  width_cm: zod.number(),
  volume_m3: zod.number(),
  estimated_repair_cost_usd: zod.number(),
  image_base64: zod.string().nullish(),
  is_fixed: zod.boolean(),
  votes: zod.number(),
  confidence: zod.number(),
  timestamp: zod.string(),
  address: zod.string().nullish(),
});
export const ListPotholesResponse = zod.array(ListPotholesResponseItem);

/**
 * @summary Report a new pothole
 */
export const CreatePotholeBody = zod.object({
  lat: zod.number(),
  lon: zod.number(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]),
  depth_cm: zod.number(),
  width_cm: zod.number(),
  volume_m3: zod.number(),
  estimated_repair_cost_usd: zod.number(),
  image_base64: zod.string().nullish(),
  confidence: zod.number(),
  address: zod.string().nullish(),
});

/**
 * @summary Get a specific pothole
 */
export const GetPotholeParams = zod.object({
  id: zod.coerce.string(),
});

export const GetPotholeResponse = zod.object({
  id: zod.string(),
  lat: zod.number(),
  lon: zod.number(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]),
  depth_cm: zod.number(),
  width_cm: zod.number(),
  volume_m3: zod.number(),
  estimated_repair_cost_usd: zod.number(),
  image_base64: zod.string().nullish(),
  is_fixed: zod.boolean(),
  votes: zod.number(),
  confidence: zod.number(),
  timestamp: zod.string(),
  address: zod.string().nullish(),
});

/**
 * @summary Update pothole (mark as fixed, add votes)
 */
export const UpdatePotholeParams = zod.object({
  id: zod.coerce.string(),
});

export const UpdatePotholeBody = zod.object({
  is_fixed: zod.boolean().optional(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]).optional(),
});

export const UpdatePotholeResponse = zod.object({
  id: zod.string(),
  lat: zod.number(),
  lon: zod.number(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]),
  depth_cm: zod.number(),
  width_cm: zod.number(),
  volume_m3: zod.number(),
  estimated_repair_cost_usd: zod.number(),
  image_base64: zod.string().nullish(),
  is_fixed: zod.boolean(),
  votes: zod.number(),
  confidence: zod.number(),
  timestamp: zod.string(),
  address: zod.string().nullish(),
});

/**
 * @summary Confirm/vote on a pothole
 */
export const VotePotholeParams = zod.object({
  id: zod.coerce.string(),
});

export const VotePotholeResponse = zod.object({
  id: zod.string(),
  lat: zod.number(),
  lon: zod.number(),
  severity: zod.enum(["Low", "Medium", "High", "Critical"]),
  depth_cm: zod.number(),
  width_cm: zod.number(),
  volume_m3: zod.number(),
  estimated_repair_cost_usd: zod.number(),
  image_base64: zod.string().nullish(),
  is_fixed: zod.boolean(),
  votes: zod.number(),
  confidence: zod.number(),
  timestamp: zod.string(),
  address: zod.string().nullish(),
});

/**
 * @summary Get dashboard summary statistics
 */
export const GetStatsSummaryResponse = zod.object({
  total_potholes: zod.number(),
  total_fixed: zod.number(),
  high_severity: zod.number(),
  total_repair_cost_usd: zod.number(),
  total_volume_m3: zod.number(),
  total_asphalt_tons: zod.number(),
  potholes_24h: zod.number(),
  avg_depth_cm: zod.number(),
  city_savings_usd: zod.number(),
});

/**
 * @summary Get detailed dashboard metrics
 */
export const GetDashboardDetailedStatsResponse = zod.object({
  severity_distribution: zod.array(
    zod.object({
      label: zod.string(),
      count: zod.number(),
      percentage: zod.number(),
      color: zod.string(),
    }),
  ),
  top_cities: zod.array(
    zod.object({
      name: zod.string(),
      region: zod.string(),
      cost: zod.number(),
      severity: zod.string(),
    }),
  ),
  regional_stats: zod.record(
    zod.string(),
    zod.object({
      total_cost: zod.number(),
      avg_severity: zod.number(),
      critical_count: zod.number(),
      high_count: zod.number(),
      city_count: zod.number(),
      severity_distribution: zod.array(
        zod.object({
          label: zod.string(),
          count: zod.number(),
          percentage: zod.number(),
        }),
      ),
      top_cities: zod.array(
        zod.object({
          name: zod.string(),
          cost: zod.number(),
          severity: zod.string(),
        }),
      ),
      notes: zod.array(
        zod.object({
          city: zod.string(),
          note: zod.string(),
          severity: zod.string(),
        }),
      ),
    }),
  ),
  cost_trend: zod.array(
    zod.object({
      month: zod.string(),
      cost: zod.number(),
      projected: zod.number().optional(),
    }),
  ),
});

/**
 * @summary Get pothole heatmap data points
 */
export const GetHeatmapDataQueryParams = zod.object({
  dateRange: zod.enum(["24h", "week", "month", "all"]).optional(),
});

export const GetHeatmapDataResponseItem = zod.object({
  lat: zod.number(),
  lon: zod.number(),
  weight: zod.number(),
});
export const GetHeatmapDataResponse = zod.array(GetHeatmapDataResponseItem);

/**
 * @summary Get driver gamification score
 */
export const GetDriverScoreResponse = zod.object({
  score: zod.number(),
  level: zod.string(),
  potholes_reported: zod.number(),
  confirmations_received: zod.number(),
  city_savings_usd: zod.number(),
  badge: zod.string(),
  next_level_threshold: zod.number(),
});

/**
 * @summary Get route with pothole warnings
 */
export const GetPotholeAwareRouteBody = zod.object({
  start_lat: zod.number(),
  start_lon: zod.number(),
  end_lat: zod.number(),
  end_lon: zod.number(),
});

export const GetPotholeAwareRouteResponse = zod.object({
  geometry: zod.object({}).passthrough().describe("GeoJSON geometry"),
  distance_m: zod.number(),
  duration_s: zod.number(),
  pothole_warnings: zod.array(
    zod.object({
      id: zod.string(),
      lat: zod.number(),
      lon: zod.number(),
      severity: zod.enum(["Low", "Medium", "High", "Critical"]),
      depth_cm: zod.number(),
      width_cm: zod.number(),
      volume_m3: zod.number(),
      estimated_repair_cost_usd: zod.number(),
      image_base64: zod.string().nullish(),
      is_fixed: zod.boolean(),
      votes: zod.number(),
      confidence: zod.number(),
      timestamp: zod.string(),
      address: zod.string().nullish(),
    }),
  ),
  has_danger: zod.boolean(),
  total_repair_cost_on_route: zod.number(),
});

/**
 * @summary List all conversations
 */
export const ListAnthropicConversationsResponseItem = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListAnthropicConversationsResponse = zod.array(
  ListAnthropicConversationsResponseItem,
);

/**
 * @summary Create a new conversation
 */
export const CreateAnthropicConversationBody = zod.object({
  title: zod.string(),
});

/**
 * @summary Get conversation with messages
 */
export const GetAnthropicConversationParams = zod.object({
  id: zod.coerce.number(),
});

export const GetAnthropicConversationResponse = zod.object({
  id: zod.number(),
  title: zod.string(),
  createdAt: zod.coerce.date(),
  messages: zod.array(
    zod.object({
      id: zod.number(),
      conversationId: zod.number(),
      role: zod.string(),
      content: zod.string(),
      createdAt: zod.coerce.date(),
    }),
  ),
});

/**
 * @summary Delete a conversation
 */
export const DeleteAnthropicConversationParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List messages in a conversation
 */
export const ListAnthropicMessagesParams = zod.object({
  id: zod.coerce.number(),
});

export const ListAnthropicMessagesResponseItem = zod.object({
  id: zod.number(),
  conversationId: zod.number(),
  role: zod.string(),
  content: zod.string(),
  createdAt: zod.coerce.date(),
});
export const ListAnthropicMessagesResponse = zod.array(
  ListAnthropicMessagesResponseItem,
);

/**
 * @summary Send a message (SSE stream)
 */
export const SendAnthropicMessageParams = zod.object({
  id: zod.coerce.number(),
});

export const SendAnthropicMessageBody = zod.object({
  content: zod.string(),
});

/**
 * @summary List complaints for a pothole
 */
export const ListComplaintsParams = zod.object({
  id: zod.coerce.string(),
});

export const ListComplaintsResponseItem = zod.object({
  id: zod.string(),
  pothole_id: zod.string(),
  type: zod.string(),
  road_type: zod.string(),
  authority: zod.string(),
  description: zod.string(),
  contact_name: zod.string().nullish(),
  contact_email: zod.string().nullish(),
  status: zod.string(),
  created_at: zod.coerce.date(),
});
export const ListComplaintsResponse = zod.array(ListComplaintsResponseItem);

/**
 * @summary File a complaint for a pothole
 */
export const CreateComplaintParams = zod.object({
  id: zod.coerce.string(),
});

export const CreateComplaintBody = zod.object({
  type: zod.enum(["complaint", "report"]),
  road_type: zod.enum([
    "NH",
    "SH",
    "MDR",
    "City Road",
    "Rural Road",
    "Unknown",
  ]),
  authority: zod.string(),
  description: zod.string(),
  contact_name: zod.string().optional(),
  contact_email: zod.string().optional(),
});
